apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-svc-8802
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-svc-8802
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
